"use client";
import { useEffect, useState } from "react";
import { can, type AdminRole, type Permission } from "../lib/rbac";
import { hasPermission, menuPermission } from "../lib/menu";
const menu=["Dashboard","Applications","Users","Rewards","Content","Survey","Offerwall","Referral","Wallet","Withdrawals","Payout","Fraud & Security","Sponsors","Affiliate","Notifications","Reports","Analytics","Settings","Staff","Audit Logs","Developer Tools","Support"];
const actions: Record<string,Permission>={"Approve withdrawal":"withdrawals.approve","Reject withdrawal":"withdrawals.reject","Edit reward":"rewards.edit","Fraud action":"fraud.action","Edit settings":"settings.edit","Payout action":"payout.action"};
export default function AdminShell({role,email}:{role:AdminRole;email:string}){const [section,setSection]=useState("Dashboard");const [dark,setDark]=useState(true);const [notice,setNotice]=useState("");useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light"},[dark]);async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.href="/login"}async function action(label:string){setNotice(`${label}: endpoint protected by RBAC and ready for API integration.`);setTimeout(()=>setNotice(""),3500)}return <div className="shell"><aside><div className="logo">REWZIO <small>ADMIN</small></div><nav>{menu.map(x=>{const p=menuPermission(x);return <button className={x===section?"active":""} key={x} onClick={()=>setSection(x)} disabled={!hasPermission(role,p)}>{x}</button>})}</nav></aside><section className="workspace"><header><div><span className="eyebrow">CONTROL CENTER</span><h1>{section}</h1></div><div className="head-actions"><span className="role">{role}</span><button onClick={()=>setDark(v=>!v)}>{dark?"☀ Light":"☾ Dark"}</button><button onClick={logout}>Sign out</button></div></header>{notice&&<div className="notice">{notice}</div>}<main className="content">{section==="Dashboard"?<Dashboard role={role}/>:<Section section={section} role={role} action={action}/>}</main><footer>{email} · {role} · RBAC enforced</footer></section></div>}
function Dashboard({role}:{role:AdminRole}){return <><div className="cards">{[["Users","—","Active accounts"],["Withdrawals","—","Review queue"],["Rewards","—","Configured rewards"],["Risk","—","Fraud review"]].map(([a,b,c])=><article key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></article>)}</div><div className="panel"><h2>Admin control plane</h2><p>Manage applications, users, rewards, content, wallet, payouts, fraud, notifications, reporting and support from one RBAC-protected console.</p><div className="chips"><span>Role: {role}</span><span>Audit trail</span><span>Feature flags</span><span>Theme</span></div></div></>}
function Section({section,role,action}:{section:string;role:AdminRole;action:(x:string)=>void}){const items=section==="Settings"?["Feature flags","App settings","Limits","Banners"]:section==="Rewards"?["Reward configuration","Daily check-in","Missions","Reward limits"]:section==="Content"?["Content management","Watch content","Legal/active status"]:section==="Withdrawals"?["Withdrawal review","Approve / reject","Capacity / limits"]:section==="Fraud & Security"?["Risk scores","Security actions","Reward holds"]:section==="Payout"?["Payout queue","Provider status","Reconciliation"]:["List / overview","Filters & search","Audit history"];const buttons=section==="Withdrawals"?["Approve withdrawal","Reject withdrawal"]:section==="Fraud & Security"?["Fraud action"]:section==="Rewards"?["Edit reward"]:section==="Settings"?["Edit settings"]:section==="Payout"?["Payout action"]:[];return <div className="panel"><span className="eyebrow">MODULE</span><h2>{section}</h2><div className="rows">{items.map(x=><div className="row" key={x}><span>{x}</span><span className="muted">Ready</span></div>)}</div>{buttons.length>0&&<div className="button-row">{buttons.map(b=><button key={b} disabled={!can(role,actions[b]!)} onClick={()=>action(b)}>{b}</button>)}</div>}{buttons.some(b=>!can(role,actions[b]!))&&<p className="muted">Some actions are ADMIN-only. STAFF never receives payout/action permissions.</p>}</div>}
