import test from 'node:test';
import assert from 'node:assert/strict';
import { AuthService } from '../dist/modules/auth/service.js';
import { createHmac } from 'node:crypto';
const cfg={jwtAccessSecret:'a'.repeat(32),otpSecret:'b'.repeat(32),googleClientId:'google-client'};
class FakeRedis{constructor(){this.counts=new Map();}async incrementWithExpiry(key){const n=(this.counts.get(key)||0)+1;this.counts.set(key,n);return n;}}
function otpHash(code){return createHmac('sha256',cfg.otpSecret).update(code).digest('hex');}
function makeDb(user={id:'u1',phone:'+62812345678',status:'ACTIVE'}){let otp;const refresh=new Map();const sessions=new Map();const users={findUnique:async()=>user,findUniqueOrThrow:async()=>user,create:async({data})=>({...user,...data}),update:async({data})=>({...user,...data})};const otpRequests={create:async({data})=>(otp={id:'otp1',...data}),findFirst:async()=>otp?.status==='PENDING'?otp:undefined,update:async({data})=>(otp={...otp,...data})};const userApps={upsert:async()=>({})};const userSessions={create:async({data})=>(sessions.set(data.id,data),data),update:async({where,data})=>{const s=sessions.get(where.id);sessions.set(where.id,{...s,...data});return s;}};const refreshTokens={create:async({data})=>{const x={id:`r${refresh.size+1}`,...data};refresh.set(data.tokenHash,x);return x;},findUnique:async({where})=>refresh.get(where.tokenHash),update:async({where,data})=>{const x=[...refresh.values()].find(v=>v.id===where.id);Object.assign(x,data);return x;},updateMany:async({where,data})=>{const x=[...refresh.values()].find(v=>v.id===where.id);if(!x||x.revokedAt!==where.revokedAt)return{count:0};Object.assign(x,data);return{count:1};}};return{users,otpRequests,userApps,userSessions,refreshTokens,$transaction:async fn=>typeof fn==='function'?fn({users,otpRequests,userApps,userSessions,refreshTokens}):Promise.all(fn)}};
test('valid OTP',async()=>{let sent;const db=makeDb();const auth=new AuthService(db,new FakeRedis(),cfg,undefined,{send:async(_p,c)=>{sent=c;}});await auth.requestOtp('app1','+62812345678');const result=await auth.verifyOtp('app1','+62812345678',sent);assert.equal(result.user.id,'u1');assert.ok(result.accessToken);assert.ok(result.refreshToken);});
test('invalid OTP',async()=>{const db=makeDb();const auth=new AuthService(db,new FakeRedis(),cfg,undefined,{send:async()=>{}});await auth.requestOtp('app1','+62812345678');await assert.rejects(()=>auth.verifyOtp('app1','+62812345678','000000'),/Invalid or expired OTP/);});
test('expired OTP',async()=>{const db=makeDb();const auth=new AuthService(db,new FakeRedis(),cfg,undefined,{send:async()=>{}});await auth.requestOtp('app1','+62812345678');db.otpRequests.findFirst=async()=>({id:'otp1',phone:'+62812345678',purpose:'LOGIN',status:'PENDING',attempts:0,codeHash:otpHash('123456'),expiresAt:new Date(Date.now()-1000)});await assert.rejects(()=>auth.verifyOtp('app1','+62812345678','123456'),/Invalid or expired OTP/);});
test('repeated OTP is rejected after consumption',async()=>{let sent;const db=makeDb();const auth=new AuthService(db,new FakeRedis(),cfg,undefined,{send:async(_p,c)=>{sent=c;}});await auth.requestOtp('app1','+62812345678');await auth.verifyOtp('app1','+62812345678',sent);await assert.rejects(()=>auth.verifyOtp('app1','+62812345678',sent),/Invalid or expired OTP/);});
test('brute force locks OTP',async()=>{const db=makeDb();const auth=new AuthService(db,new FakeRedis(),cfg,undefined,{send:async()=>{}});await auth.requestOtp('app1','+62812345678');for(let i=0;i<4;i++)await assert.rejects(()=>auth.verifyOtp('app1','+62812345678','000000'));await assert.rejects(()=>auth.verifyOtp('app1','+62812345678','000000'),/Too many verification attempts/);});
test('refresh rotation revokes previous token',async()=>{let sent;const db=makeDb();const auth=new AuthService(db,new FakeRedis(),cfg,undefined,{send:async(_p,c)=>{sent=c;}});await auth.requestOtp('app1','+62812345678');const first=await auth.verifyOtp('app1','+62812345678',sent);const second=await auth.refresh('app1',first.refreshToken);assert.notEqual(second.refreshToken,first.refreshToken);await assert.rejects(()=>auth.refresh('app1',first.refreshToken),/Invalid refresh token/);});
test('logout revokes session',async()=>{let sent;const db=makeDb();const auth=new AuthService(db,new FakeRedis(),cfg,undefined,{send:async(_p,c)=>{sent=c;}});await auth.requestOtp('app1','+62812345678');const first=await auth.verifyOtp('app1','+62812345678',sent);await auth.logout(first.refreshToken);await assert.rejects(()=>auth.refresh('app1',first.refreshToken),/Invalid refresh token/);});
test('suspended account is rejected',async()=>{let sent;const db=makeDb({id:'u2',phone:'+62812345678',status:'SUSPENDED'});const auth=new AuthService(db,new FakeRedis(),cfg,undefined,{send:async(_p,c)=>{sent=c;}});await auth.requestOtp('app1','+62812345678');await assert.rejects(()=>auth.verifyOtp('app1','+62812345678',sent),/Account is suspended/);});
