import type { Env } from '../worker.js';

const ACCESS_TTL=900,REFRESH_TTL=2592000,OTP_TTL=300,OTP_MAX_ATTEMPTS=5; const enc=new TextEncoder();
export interface AuthConfig{jwtAccessSecret:string;otpSecret:string;googleClientId:string;}
export interface AuthResult{accessToken:string;refreshToken:string;expiresIn:number;user:{id:string;phone:string|null;status:string};}
async function hmac(secret:string,value:string):Promise<string>{const k=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return base64url(new Uint8Array(await crypto.subtle.sign('HMAC',k,enc.encode(value))));}
async function sha256(value:string):Promise<string>{return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(value))));}
function base64url(bytes:Uint8Array):string{let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
function jsonb(v:unknown):string{return base64url(enc.encode(JSON.stringify(v)));} function randomHex(n:number):string{const a=new Uint8Array(n);crypto.getRandomValues(a);return hex(a);} function hex(a:Uint8Array):string{return Array.from(a,b=>b.toString(16).padStart(2,'0')).join('');} function now():string{return new Date().toISOString();}
function err(code:string,message:string,status=401):Error&{statusCode:number;code:string}{const e=Object.assign(new Error(message),{statusCode:status,code});return e;} function requiredPhone(v:string):string{const p=v.replace(/[\s()-]/g,'');if(!/^\+?[1-9]\d{7,14}$/.test(p))throw err('INVALID_PHONE','Invalid phone number',400);return p.startsWith('+')?p:`+${p}`;}
export async function requestOtp(env:Env,c:AuthConfig,appId:string,phone:string,ip?:string):Promise<void>{const p=requiredPhone(phone),code=String(100000+crypto.getRandomValues(new Uint32Array(1))[0]%900000),t=now();await env.DB.prepare(`INSERT INTO otp_requests (id,appId,phone,purpose,codeHash,status,attempts,expiresAt,ipAddress,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).bind(randomHex(16),appId,p,'LOGIN',await hmac(c.otpSecret,code),'PENDING',0,new Date(Date.now()+OTP_TTL*1000).toISOString(),ip??null,t,t).run();}
export async function verifyOtp(env:Env,c:AuthConfig,appId:string,phone:string,code:string,ip?:string):Promise<AuthResult>{const p=requiredPhone(phone),r=await env.DB.prepare(`SELECT * FROM otp_requests WHERE appId=? AND phone=? AND purpose='LOGIN' AND status='PENDING' ORDER BY createdAt DESC LIMIT 1`).bind(appId,p).first<Record<string,unknown>>();if(!r)throw err('INVALID_OTP','Invalid or expired OTP');const id=String(r.id),attempts=Number(r.attempts??0);if(Date.parse(String(r.expiresAt))<=Date.now()){await env.DB.prepare(`UPDATE otp_requests SET status='EXPIRED',updatedAt=? WHERE id=?`).bind(now(),id).run();throw err('OTP_EXPIRED','Invalid or expired OTP');}if(attempts>=OTP_MAX_ATTEMPTS)throw err('OTP_LOCKED','Too many verification attempts');if(await hmac(c.otpSecret,code)!==String(r.codeHash)){const n=attempts+1;await env.DB.prepare(`UPDATE otp_requests SET attempts=?,status=?,updatedAt=? WHERE id=?`).bind(n,n>=OTP_MAX_ATTEMPTS?'LOCKED':'PENDING',now(),id).run();throw err(n>=OTP_MAX_ATTEMPTS?'OTP_LOCKED':'INVALID_OTP',n>=OTP_MAX_ATTEMPTS?'Too many verification attempts':'Invalid or expired OTP');}let u=await env.DB.prepare(`SELECT id,phone,status FROM users WHERE phone=? LIMIT 1`).bind(p).first<{id:string;phone:string|null;status:string}>();if(!u){const id2=randomHex(16),t=now();await env.DB.prepare(`INSERT INTO users (id,phone,phoneVerifiedAt,status,referralCode,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?)`).bind(id2,p,t,'ACTIVE',randomHex(8),t,t).run();u={id:id2,phone:p,status:'ACTIVE'};}if(u.status!=='ACTIVE')throw err('ACCOUNT_SUSPENDED','Account is suspended',403);const t=now();await env.DB.batch([env.DB.prepare(`UPDATE otp_requests SET status='VERIFIED',consumedAt=?,updatedAt=? WHERE id=?`).bind(t,t,id),env.DB.prepare(`INSERT INTO user_apps (id,appId,userId,status,firstSeenAt,lastSeenAt,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(appId,userId) DO UPDATE SET lastSeenAt=excluded.lastSeenAt,updatedAt=excluded.updatedAt`).bind(randomHex(16),appId,u.id,'ACTIVE',t,t,t,t),env.DB.prepare(`UPDATE users SET phoneVerifiedAt=?,lastLoginAt=?,updatedAt=? WHERE id=?`).bind(t,t,t,u.id)]);return issueSession(env,c,appId,u.id,u.phone,ip);}
async function issueSession(env:Env,c:AuthConfig,appId:string,userId:string,phone:string|null,ip?:string):Promise<AuthResult>{const sid=randomHex(16),raw=randomHex(48),hash=await sha256(raw),t=now(),expires=new Date(Date.now()+REFRESH_TTL*1000).toISOString();await env.DB.batch([env.DB.prepare(`INSERT INTO user_sessions (id,appId,userId,tokenHash,status,expiresAt,lastSeenAt,ipAddress,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(sid,appId,userId,hash,'ACTIVE',expires,t,ip??null,t,t),env.DB.prepare(`INSERT INTO refresh_tokens (id,appId,userId,sessionId,tokenHash,expiresAt,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?)`).bind(randomHex(16),appId,userId,sid,hash,expires,t,t)]);return{accessToken:await accessToken(c.jwtAccessSecret,userId,appId,sid),refreshToken:raw,expiresIn:ACCESS_TTL,user:{id:userId,phone,status:'ACTIVE'}};}
async function accessToken(secret:string,userId:string,appId:string,sid:string):Promise<string>{const iat=Math.floor(Date.now()/1000),input=`${jsonb({alg:'HS256',typ:'JWT'})}.${jsonb({sub:userId,appId,sid,iat,exp:iat+ACCESS_TTL})}`;return`${input}.${await hmac(secret,input)}`;}
export async function refresh(env:Env,c:AuthConfig,appId:string,raw:string):Promise<AuthResult>{const hash=await sha256(raw),r=await env.DB.prepare(`SELECT * FROM refresh_tokens WHERE tokenHash=? LIMIT 1`).bind(hash).first<Record<string,unknown>>();if(!r||r.revokedAt||Date.parse(String(r.expiresAt))<=Date.now()||String(r.appId)!==appId)throw err('INVALID_REFRESH_TOKEN','Invalid refresh token');const u=await env.DB.prepare(`SELECT id,phone,status FROM users WHERE id=?`).bind(String(r.userId)).first<{id:string;phone:string|null;status:string}>();if(!u||u.status!=='ACTIVE')throw err('INVALID_REFRESH_TOKEN','Invalid refresh token');const next=randomHex(48),nh=await sha256(next),t=now(),results=await env.DB.batch([env.DB.prepare(`UPDATE refresh_tokens SET revokedAt=?,updatedAt=? WHERE id=? AND revokedAt IS NULL`).bind(t,t,String(r.id)),env.DB.prepare(`INSERT INTO refresh_tokens (id,appId,userId,sessionId,tokenHash,expiresAt,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?)`).bind(randomHex(16),appId,u.id,String(r.sessionId??'')||null,nh,new Date(Date.now()+REFRESH_TTL*1000).toISOString(),t,t)]);if((results[0]?.meta.changes??0)!==1)throw err('INVALID_REFRESH_TOKEN','Invalid refresh token');return{accessToken:await accessToken(c.jwtAccessSecret,u.id,appId,String(r.sessionId??'')),refreshToken:next,expiresIn:ACCESS_TTL,user:u};}
export async function googleLogin(env:Env,c:AuthConfig,appId:string,idToken:string,ip?:string):Promise<AuthResult>{const res=await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${encodeURIComponent(idToken)}`);if(!res.ok)throw err('INVALID_GOOGLE_TOKEN','Invalid Google credential');const d=await res.json() as{aud?:string;sub?:string;email_verified?:boolean|string};if(d.aud!==c.googleClientId||!d.sub||(d.email_verified!==true&&d.email_verified!=='true'))throw err('INVALID_GOOGLE_TOKEN','Invalid Google credential');let u=await env.DB.prepare(`SELECT id,phone,status FROM users WHERE googleSubject=? LIMIT 1`).bind(d.sub).first<{id:string;phone:string|null;status:string}>();if(!u){const id=randomHex(16),t=now();await env.DB.prepare(`INSERT INTO users (id,googleSubject,status,referralCode,createdAt,updatedAt) VALUES (?,?,?,?,?,?)`).bind(id,d.sub,'ACTIVE',randomHex(8),t,t).run();u={id,phone:null,status:'ACTIVE'};}if(u.status!=='ACTIVE')throw err('ACCOUNT_SUSPENDED','Account is suspended',403);const t=now();await env.DB.prepare(`INSERT INTO user_apps (id,appId,userId,status,firstSeenAt,lastSeenAt,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(appId,userId) DO UPDATE SET lastSeenAt=excluded.lastSeenAt,updatedAt=excluded.updatedAt`).bind(randomHex(16),appId,u.id,'ACTIVE',t,t,t,t).run();return issueSession(env,c,appId,u.id,u.phone,ip);}
export async function logout(env:Env,raw:string):Promise<void>{const h=await sha256(raw),r=await env.DB.prepare(`SELECT id,sessionId FROM refresh_tokens WHERE tokenHash=?`).bind(h).first<{id:string;sessionId:string|null}>();if(!r)return;const t=now(),s=[env.DB.prepare(`UPDATE refresh_tokens SET revokedAt=?,updatedAt=? WHERE id=?`).bind(t,t,r.id)];if(r.sessionId)s.push(env.DB.prepare(`UPDATE user_sessions SET status='REVOKED',revokedAt=?,updatedAt=? WHERE id=?`).bind(t,t,r.sessionId));await env.DB.batch(s);}
