import { EconomicCoordinator } from './economic-coordinator.js';
import { googleLogin, logout, refresh, requestOtp, verifyOtp, type AuthConfig } from './cloudflare/auth.js';

export interface Env { DB:D1Database; REWZIO_DATABASE_NAME:string; ENVIRONMENT:string; ECONOMIC_COORDINATOR:DurableObjectNamespace; PAYOUT_QUEUE:Queue; JWT_ACCESS_SECRET:string; OTP_SECRET:string; GOOGLE_CLIENT_ID:string; }
function json(data:unknown,status=200):Response{return Response.json(data,{status,headers:{'Cache-Control':'no-store'}});}
function config(env:Env):AuthConfig{return{jwtAccessSecret:env.JWT_ACCESS_SECRET,otpSecret:env.OTP_SECRET,googleClientId:env.GOOGLE_CLIENT_ID};}
async function body(request:Request):Promise<Record<string,unknown>>{const value=await request.json().catch(()=>null);if(!value||typeof value!=='object')throw Object.assign(new Error('Invalid JSON body'),{statusCode:400,code:'BAD_REQUEST'});return value as Record<string,unknown>;}
function required(b:Record<string,unknown>,key:string):string{const v=b[key];if(typeof v!=='string'||!v)throw Object.assign(new Error(`${key} is required`),{statusCode:400,code:'BAD_REQUEST'});return v;}
async function health(env:Env):Promise<Response>{let database='unavailable';try{await env.DB.prepare('SELECT 1 AS ok').first();database='ok';}catch{database='not-bound';}return json({status:'ok',service:'rewzio-api',runtime:'cloudflare-workers',environment:env.ENVIRONMENT,database:env.REWZIO_DATABASE_NAME,databaseStatus:database,apiVersion:'v1'});}
async function migrationStatus(env:Env):Promise<Response>{try{const row=await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all<{name:string}>();return json({status:'ok',database:env.REWZIO_DATABASE_NAME,tables:row.results.map(x=>x.name)});}catch(e){return json({status:'error',message:e instanceof Error?e.message:'database error'},500);}}
async function authRoute(request:Request,env:Env,path:string):Promise<Response|null>{if(!path.startsWith('/api/v1/auth/'))return null;try{if(request.method!=='POST')return json({error:{code:'METHOD_NOT_ALLOWED',message:'POST required'}},405);const b=await body(request),c=config(env),appId=required(b,'appId'),ip=request.headers.get('CF-Connecting-IP')??undefined;if(path==='/api/v1/auth/request-otp'){await requestOtp(env,c,appId,required(b,'phone'),ip);return json({data:{requested:true}});}if(path==='/api/v1/auth/verify-otp')return json({data:await verifyOtp(env,c,appId,required(b,'phone'),required(b,'code'),ip)});if(path==='/api/v1/auth/google')return json({data:await googleLogin(env,c,appId,required(b,'idToken'),ip)});if(path==='/api/v1/auth/refresh')return json({data:await refresh(env,c,appId,required(b,'refreshToken'))});if(path==='/api/v1/auth/logout'){await logout(env,required(b,'refreshToken'));return json({data:{loggedOut:true}});}return json({error:{code:'NOT_FOUND',message:'Auth endpoint not found'}},404);}catch(e){const x=e as Error&{statusCode?:number;code?:string};return json({error:{code:x.code??'BAD_REQUEST',message:x.message||'Request failed'}},x.statusCode??400);}}
const worker={async fetch(request:Request,env:Env):Promise<Response>{const url=new URL(request.url);if(request.method==='GET'&&url.pathname==='/health')return health(env);if(request.method==='GET'&&url.pathname==='/api/v1')return json({data:{service:'rewzio-api',version:'v1'}});if(request.method==='GET'&&url.pathname==='/api/v1/migration/status')return migrationStatus(env);const auth=await authRoute(request,env,url.pathname);if(auth)return auth;const economic=url.pathname.match(/^\/api\/v1\/economic\/([^/]+)$/);if(economic&&request.method==='POST'){const id=env.ECONOMIC_COORDINATOR.idFromName(decodeURIComponent(economic[1]));return env.ECONOMIC_COORDINATOR.get(id).fetch(request);}return json({error:{code:'MIGRATION_IN_PROGRESS',message:'This API surface is not yet migrated to the Cloudflare runtime.'}},503);},async queue(batch:MessageBatch<unknown>):Promise<void>{for(const message of batch.messages)message.retry({delaySeconds:30});}};
export{EconomicCoordinator};export default worker;
