import { EconomicCoordinator } from './economic-coordinator.js';
import { googleLogin, logout, refresh, requestOtp, verifyOtp, type AuthConfig } from './cloudflare/auth.js';
export interface Env{DB:D1Database;REWZIO_DATABASE_NAME:string;ENVIRONMENT:string;ECONOMIC_COORDINATOR:DurableObjectNamespace;PAYOUT_QUEUE:Queue;JWT_ACCESS_SECRET:string;OTP_SECRET:string;GOOGLE_CLIENT_ID:string;}
const json=(d:unknown,s=200)=>Response.json(d,{status:s,headers:{'Cache-Control':'no-store'}});const cfg=(e:Env):AuthConfig=>({jwtAccessSecret:e.JWT_ACCESS_SECRET,otpSecret:e.OTP_SECRET,googleClientId:e.GOOGLE_CLIENT_ID});
async function readBody(r:Request):Promise<Record<string,unknown>>{const v=await r.json().catch(()=>null);if(!v||typeof v!=='object')throw Object.assign(new Error('Invalid JSON body'),{statusCode:400,code:'BAD_REQUEST'});return v as Record<string,unknown>;}
function req(b:Record<string,unknown>,k:string):string{const v=b[k];if(typeof v!=='string'||!v)throw Object.assign(new Error(`${k} is required`),{statusCode:400,code:'BAD_REQUEST'});return v;}
async function health(e:Env){let database='unavailable';try{await e.DB.prepare('SELECT 1 AS ok').first();database='ok';}catch{}return json({status:'ok',service:'rewzio-api',runtime:'cloudflare-workers',environment:e.ENVIRONMENT,database:e.REWZIO_DATABASE_NAME,databaseStatus:database,apiVersion:'v1'});}
async function migrationStatus(e:Env){try{const r=await e.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all<{name:string}>();return json({status:'ok',database:e.REWZIO_DATABASE_NAME,tables:r.results.map(x=>x.name)});}catch(x){return json({status:'error',message:x instanceof Error?x.message:'database error'},500);}}
async function authRoute(r:Request,e:Env,path:string):Promise<Response|null>{if(!path.startsWith('/api/v1/auth/'))return null;if(r.method!=='POST')return json({error:{code:'METHOD_NOT_ALLOWED',message:'POST required'}},405);try{const b=await readBody(r),c=cfg(e),appId=req(b,'appId'),ip=r.headers.get('CF-Connecting-IP')??undefined;if(path==='/api/v1/auth/request-otp'){await requestOtp(e,c,appId,req(b,'phone'),ip);return json({data:{requested:true}});}if(path==='/api/v1/auth/verify-otp')return json({data:await verifyOtp(e,c,appId,req(b,'phone'),req(b,'code'),ip)});if(path==='/api/v1/auth/google')return json({data:await googleLogin(e,c,appId,req(b,'idToken'),ip)});if(path==='/api/v1/auth/refresh')return json({data:await refresh(e,c,appId,req(b,'refreshToken'))});if(path==='/api/v1/auth/logout'){await logout(e,req(b,'refreshToken'));return json({data:{loggedOut:true}});}return json({error:{code:'NOT_FOUND',message:'Auth endpoint not found'}},404);}catch(x){const z=x as Error&{statusCode?:number;code?:string};return json({error:{code:z.code??'BAD_REQUEST',message:z.message||'Request failed'}},z.statusCode??400);}}
const worker={async fetch(r:Request,e:Env){const u=new URL(r.url);if(r.method==='GET'&&u.pathname==='/health')return health(e);if(r.method==='GET'&&u.pathname==='/api/v1')return json({data:{service:'rewzio-api',version:'v1'}});if(r.method==='GET'&&u.pathname==='/api/v1/migration/status')return migrationStatus(e);const a=await authRoute(r,e,u.pathname);if(a)return a;const m=u.pathname.match(/^\/api\/v1\/economic\/([^/]+)$/);if(m&&r.method==='POST'){const id=e.ECONOMIC_COORDINATOR.idFromName(decodeURIComponent(m[1]));return e.ECONOMIC_COORDINATOR.get(id).fetch(r);}return json({error:{code:'MIGRATION_IN_PROGRESS',message:'This API surface is not yet migrated to the Cloudflare runtime.'}},503);},async queue(batch:MessageBatch<unknown>){for(const message of batch.messages)message.retry({delaySeconds:30});}};export{EconomicCoordinator};export default worker;
